#ifndef SNAKE_CONSTANTS_H
#define SNAKE_CONSTANTS_H

/* Initial window dimensions */
#define WINDOW_WIDTH_INITIAL 800
#define WINDOW_HEIGHT_INITIAL 640

/* Framerate constants */
#define MAX_FPS 30
#define MS_PER_FRAME 1000 / MAX_FPS

/* Snake Constants */
#define SNAKE_MOVE_DELAY_DECREMENT_MS 20
#define SNAKE_MOVE_DELAY_MIN_MS 50

/* Render constants */
#define WINDOW_BORDER_THICKNESS 4
#define WINDOW_BORDER_COLOR 0xaa, 0xaa, 0xaa

#define MENU_HEIGHT 40
#define MENU_EXIT_BUTTON_COLOR 0xee, 0x00, 0x00
#define MENU_EXIT_BUTTON_COLOR_HOVER 0xff, 0x66, 0x66
#define MENU_EXIT_BUTTON_W 40
#define MENU_EXIT_BUTTON_H MENU_HEIGHT
#define MENU_EXIT_BUTTON_X (WINDOW_WIDTH_INITIAL - WINDOW_BORDER_THICKNESS - MENU_EXIT_BUTTON_W)
#define MENU_EXIT_BUTTON_Y WINDOW_BORDER_THICKNESS

#define GRID_COLOR 0x66, 0x66, 0x66
#define GRID_COUNT_X 40
#define GRID_COUNT_Y 30
#define GRID_X WINDOW_BORDER_THICKNESS
#define GRID_Y (WINDOW_BORDER_THICKNESS + MENU_HEIGHT + WINDOW_BORDER_THICKNESS)
#define GRID_WIDTH (WINDOW_WIDTH_INITIAL - GRID_X - WINDOW_BORDER_THICKNESS)
#define GRID_HEIGHT (WINDOW_HEIGHT_INITIAL - GRID_Y - WINDOW_BORDER_THICKNESS)
#define GRID_CELL_WIDTH ((float)GRID_WIDTH / (float)GRID_COUNT_X)
#define GRID_CELL_HEIGHT ((float)GRID_HEIGHT / (float)GRID_COUNT_Y)

#define SNAKE_COLOR 0xff, 0xff, 0xff

#define OVERLAY_PAUSE_COLOR 0xff, 0xff, 0xff
#define OVERLAY_DEAD_COLOR 0xff, 0x00, 0x00

#define FOOD_COLOR 0xff, 0x00, 0x00

/* end Render constants */

#endif /* SNAKE_CONSTANTS_H */
